### ISSUE TITLE
harfbuzz.pc problem

### ISSUE THREAD

**Issue by arnabanimesh** [msys2/MSYS2-packages#2249] opened 2020-12-06 23:52 UTC
## Describe the issue

`harfbuzz.pc` is corrupted

## Steps to Reproduce the Problem

1. Compile a `Rust` project with `cairo-rs` dependency and set `PKG_CONFIG_PATH` to use `C:\msys64\mingw64\lib\pkgconfig`
2. The following error appears: **[Click here](https://gist.github.com/arnabanimesh/789dd5529fe9b1bd302f147480d432e1)**
3. Successful compilation should happen like what happens when I use the `gtk3` build used by the [`gvsbuild`](https://github.com/wingtk/gvsbuild). But it is dynamically compiled so I can't use it. I need statically compiled libs.

## Additional Context: Operating System, Screenshots

OS: Windows 10 Home version 1909 64bit
Screenshots: N.A.

**Comment by arnabanimesh** [comment] 2020-12-07 04:43
Source code of the project is mentioned in this [Github Gist](https://gist.github.com/arnabanimesh/77d4c63ea710d2a72b26ea57ae922eda). Ignore the logs.

**Comment by lazka** [comment] 2020-12-08 08:11
I guess this is a duplicate of https://github.com/msys2/MINGW-packages/issues/7399

**Closed by lazka** 2020-12-08 08:11 UTC
