### ISSUE TITLE
Slow filesystem access with bash-4.4.023-2

### ISSUE THREAD

**Issue by mscriv7** [msys2/MSYS2-packages#1871] opened 2020-02-25 04:10 UTC
Hello,

Slow filesystem access with bash-4.4.023-2 with MSYS2 64bit

Slow local filesystem access observed with bash-4.4.023-2 that is not seen with bash-4.4-023-1.

To verify this I performed a fresh install of MSYS 64bit into C:\msys64 and executed a simple cat of a 7 byte text file. With this test I observed a realtime duration of approximately 110ms for 4.4.023-1 and 350ms for 4.4.023-2.

# Test
## Install bash-4.4.023-1
pacman -U bash-4.4.023-1-x86_64.pkg.tar.xz
## Launch MSYS from shortcut.
echo msys64>file
for i in {1..10}; do time cat file; done
Average: ~0.110s

## Install bash-4.4.023-2
pacman -U bash-4.4.023-2-x86_64.pkg.tar.xz
## Launch MSYS from shortcut.
echo msys64>file
for i in {1..10}; do time cat file; done
Average: ~0.350s

Notes:
- When I compared the source packages and confirmed only a build change the difference in performance seemed unreasonable so I re-tested to confirm the result.
- Now that I am running bash-4.4.023-1 the overall responsiveness of MSYS feels improved.

**Comment by lazka** [comment] 2020-02-25 08:30
I can't reproduce, ~0.009s here.

**Comment by mscriv7** [comment] 2020-02-25 11:48
Damn, thanks.
I am running MSYS2 on a managed PC but I found an excluded directory and so confirmed what you stated. It is ~0.110s with both versions of bash in the excluded directory. I guess there is something in the newer bash.exe that the AV does not like.

**Comment by lazka** [comment] 2020-02-26 08:03
ok, thanks for testing. Sadly nothing we can do here, so closing.

**Closed by lazka** 2020-02-26 08:03 UTC

**Comment by jcrben** [comment] 2023-02-09 19:46
@lazka interesting that you've got ~0.009s - I get ~0.1s with the same script using both bash 4.4 and bash 5.2 - wondering if there's some tips somewhere on how to improve performance - maybe it is that antivirus thing as I am on a managed pc

**Comment by lazka** [comment] 2023-02-09 20:49
There are no new tips since then, besides not having cygwin/bash in your hot path.

Some clarification on the example above, it is likely slow because it creates a new process for every "cat" call, and not due to file IO.

**Comment by jcrben** [comment] 2023-02-10 08:08
What does "not having cygwin/bash in your hot path" mean?

**Comment by lazka** [comment] 2023-02-10 08:11
Assuming that you are annoyed by some part of your workflow being slow, try to not use bash or other cygwin based tools for the things that are slow.

**Comment by jcrben** [comment] 2023-02-10 08:15
I'm ok with the performance - hardly noticeable to me - but I'd like to get more coworkers over and some of them are persnickety about the difference from native Windows tools. Will continue working on polishing up WSL.

**Comment by OopsLouie** [comment] 2025-05-19 09:36
hi ghost, i need old package of msys-bash-4.4.023, and i can't find it anywhere over the Internet.
do you have local cache? I really need it!

**Comment by sskras** [comment] 2025-05-19 09:57
Nick of the ghost was @mscriv7, BTW. Hopefully it's [Mark Scrivener](https://medium.com/@mscriv7) :)
