### ISSUE TITLE
Install or extract do not finish in docker, with mcr.microsoft.com/windows/servercore:2009-amd64

### ISSUE THREAD

**Issue by greenkalx** [msys2/MSYS2-packages#3361] opened 2022-12-03 05:55 UTC
Both installer and tarball fail to fully install in docker.

The installer does extract partially, but is missing bash.exe and pacman.exe
For the installer, I am running:
```
Invoke-WebRequest https://github.com/msys2/msys2-installer/releases/download/2022-01-18/msys2-base-x86_64-20220118.sfx.exe -Outfile C:\tools\msys-setup.exe;
Start-Process "C:\tools\msys-setup.exe" -ArgumentList "-y -oC:\ " -Wait
```

The tarball extracts more, including bash.exe but is missing pacman.exe.
For the tarball, I am running:
```
Invoke-WebRequest http://repo.msys2.org/distrib/msys2-x86_64-latest.tar.xz -Outfile C:\tools\msys2.tar.xz
Start-process "7z" -ArgumentList "e C:\tools\msys2.tar.xz -oC:\tools " -NoNewWindow -Wait
Start-process "7z" -ArgumentList "x C:\tools\msys2.tar -oC:\ " -NoNewWindow -Wait
```

I have tried running docker 'build' and docker 'run':
```
docker build --memory 2GB --isolation process --build-arg BASE_TAG=$BASE_TAG --tag $TAG $COMPOSE_DIR

docker run -it --memory 2GB --isolation process docker-virtual.artifactory.york.lan/windows/servercore:2009-amd64 powershell
```

Wonder if it's due to permissions or antivirus (Carbon Black or Endpoint Protector).

I have tried other installers:
```
https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe
https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-x86_64-latest.exe
```
And other tarballs:
```
https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.tar.xz 
```

This was running for us with previous Windows versions, 1809-amd64 and 1909-amd64.

**Comment by greenkalx** [comment] 2022-12-03 05:55
These other installers are working in the same Docker container:
vs_buildtools.exe, winsdksetup.exe, 7z2107-x64.exe, PortableGit-2.27.0-64-bit.7z.exe, python-3.7.8-embed-amd64.zip, cmake-3.18.0-win64-x64.zip, nasm-2.15.03-win64.zip, v1.10.0/ninja-win.zip, strawberry-perl-5.28.2.1-64bit-portable.zip

**Comment by lazka** [comment] 2022-12-03 10:59
Duplicate of https://github.com/msys2/msys2-installer/issues/58

**Closed by lazka** 2022-12-03 10:59 UTC
