### ISSUE TITLE
[BUG]mintty charset problem not yet fixed

### ISSUE THREAD

**Issue by yxl0756** [msys2/MSYS2-packages#2012] opened 2020-06-13 01:42 UTC
msys2-runtime version: 3.1.5-3,
mintty version: 3.1.7

$ echo $LANG
en_US.UTF-8
$ cat test.c
```
#include <stdio.h>
int main(void){
    unsigned char utf8[]={0xE4,0xBD,0xA0,0xE5,0xA5,0xBD,0x00};
    printf("%s\n", utf8);
    return 0;
}
```
$ x86_64-pc-msys-gcc -o test1.exe test.c -O2 -s
$ x86_64-w64-mingw32-gcc -o test2.exe test.c -O2 -s
$ ./test1.exe
你好                                -- correct output
$ ./test2.exe
浣犲ソ                             -- incorrect output
$ objdump -x test1.exe|grep "DLL Name"
        DLL Name: msys-2.0.dll
        DLL Name: KERNEL32.dll

$ objdump -x test2.exe|grep "DLL Name"
        DLL Name: KERNEL32.dll
        DLL Name: msvcrt.dll

**Comment by nobk** [comment] 2020-07-02 03:52
You should post mintty issue here
https://github.com/mintty/mintty/issues

**Comment by Biswa96** [comment] 2020-07-02 04:24
Mintty is updated since then. Try the new version.

**Comment by mati865** [comment] 2020-07-02 08:08
I think it's duplicate of https://github.com/msys2/MSYS2-packages/issues/1974

**Comment by yxl0756** [comment] 2020-07-11 15:33
> 
> 
> Mintty is updated since then. Try the new version.

The problem should be in the upstream's cygwin
I used the old version of msys-2.0.dll to replace the current version, it can display utf8 characters normally
However, this replacement may affect other applications.

**Comment by dscho** [comment] 2020-09-01 13:30
> I think it's duplicate of #1974

I think so, too. The workaround seems to be to call `cmd //c chcp 65001`.

@lazka should we close this issue in favor of #1974?

**Comment by dscho** [comment] 2020-09-24 10:28
Could you re-test with the latest MSYS2 runtime, please?

**Comment by yxl0756** [comment] 2020-09-24 13:26
> 
> 
> Could you re-test with the latest MSYS2 runtime, please?

I upgraded to the latest version, msys2-runtime-3.1.7-2, mintty-3.4.0-1
the issue seems to have been fixed. thanks!

**Closed** 2020-09-24 13:41 UTC
Labels: bug
