### ISSUE TITLE
Windows defender warns mingw-w64-x86_64-gcc package includes malware

### ISSUE THREAD

**Issue by yasuhirokimura** [msys2/MSYS2-packages#2734] opened 2021-12-11 20:16 UTC
While updating `mingw-w64-x86_64-gcc` package to latest version, Windows defender warns it includes malware and removes `/mingw64/lib/gcc/x86_64-w64-mingw32/11.2.0/cc1.exe`. I updated signature of Windows defender but the issue still happens. Probably it is false positive. But I don't know how to stop Windows defender from removing it.

OS is Windows 10 version 21H2.

**Comment by MehdiChinoune** [comment] 2021-12-11 21:35
duplicate of https://github.com/msys2/MINGW-packages/issues/10295

**Closed** 2021-12-11 21:49 UTC
