### ISSUE TITLE
bash causing garbage output in TUI applications

### ISSUE THREAD

**Issue by goyalyashpal** [msys2/MSYS2-packages#3515] opened 2023-01-25 16:23 UTC
hi!

### Problem
* bash 5.1.8 caused applications to output garbage (raw color codes i guess)
* current bash `5.2.9(1)-release (x86_64-pc-msys)` is running that fine.

But neither the actual cause, nor the fixing commit was not documented.

### Filed issues elsewhere
* https://github.com/wez/wezterm/issues/2294
* https://github.com/helix-editor/helix/issues/2953

### Action
* Do you have any idea on what might have caused/fixed that?
i tried looking at [commit history] for [MSYS2-packages/bash] but couldnt find out much relevant stuff from commit messages
* Ideally, I want to know/find out which commit fixed the issue 
But knowing the oldest fixing release version would be good too.
* How can i install the older version of a package? 
Again, ideally, i would have wanted to try running git bisect here, but i don't know building etc, so, i will just suffice at running only the prebuild package versions.

[commit history]: https://github.com/msys2/MSYS2-packages/commits/master?beforer=b7f270714eacd849c876ddfd317e43115e07d44d+1&branch=master&path%5B%5D=bash&qualified_name=refs%2Fheads%2Fmaster
[MSYS2-packages/bash]: https://packages.msys2.org/base/bash

**Comment by Biswa96** [comment] 2023-01-25 17:24
Please provide the steps to reproduce the issue. Not all users are familiar with those programs.

**Comment by yashpalgoyal1304** [comment] 2023-01-25 17:26
wait, on it now

**Comment by yashpalgoyal1304** [comment] 2023-01-25 17:55
### Steps to reproduce:

1. Launch a terminal _with_ bash (from msys: version 5.1.8, avoid git-bash[^gfw] for now)
    - a. `mintty -e bash`
   - b. `wezterm start bash` or `alacritty -e bash`
   - c. `conhost bash`
2. Launch bash (from msys - version 5.1.8) in that terminal
3. Launch `hx`
4. Update `bash` to version `GNU bash, version 5.2.9(1)-release (x86_64-pc-msys)` but keep the `hx` and the terminal version same.
5. Repeat step 1 to 3
6. Repeat step 1 to 3 again, but now, replacing `bash` with `cmd`

[^gfw]: it happens for the bash from gfw (git for windows) too, but i don't know the version thereof _and_ also it gets a lot tricky to keep track of the terminal and correct bash version etc, so, just leave it for now...

### Possible Outcomes:

Buggy one:
<img src="https://user-images.githubusercontent.com/19423063/214639784-d5f03791-1e65-4bdd-b5fd-31430a5c75c4.png" width=400px/>

Correct one:
<img src="https://user-images.githubusercontent.com/19423063/214639591-8b834679-b5c0-4ac1-9a2b-03de0f1e5875.png" width=400px/>

### My observations:

1. `mintty` will show correct output with both bash versions
2. `wezterm` and `alacritty` show buggy output with old bash version, but correct output with new bash version
3. `conhost` shows buggy output with both bash bash versions
4. all of these show correct output if step 2 is ommitted and some other shell like `cmd` is used instead

### Conclusion
Owing to observation 2 and 4, it should mean that the bug is in the older bash.

**Comment by yashpalgoyal1304** [comment] 2023-01-25 17:56
here's a video recording of it, it's quite long (1 minute) so, sorry for it....


https://user-images.githubusercontent.com/19423063/180470975-a1c443d4-6d29-4ba5-a397-5a3445e90d7d.mp4

**Comment by yashpalgoyal1304** [comment] 2023-01-25 19:06
here's the package history* for bash from <tt>/var/log/[pacman.log]</tt>

```log
[2021-07-25] [ALPM] installed bash (5.1.008-1)
[2022-06-18] [ALPM] upgraded bash (5.1.008-1 -> 5.1.016-1)
[2022-12-26] [ALPM] upgraded bash (5.1.016-1 -> 5.2.009-1)
```


[package history]: https://duckduckgo.com/?q=checking+package+history+in+pacman&t=vivaldi&ia=web
[pacman.log]: https://bbs.archlinux.org/viewtopic.php?id=88600

**Comment by yashpalgoyal1304** [comment] 2023-01-25 19:17
oh gosh, this is going to be a mystery...
* the issue i filled on wezterm was from 2022-07-22,
* the [reported working date] is 2022-12-06; 
* and no update of bash took place on my system in between those dates as seen from above log...

So, bash might not be the culprit... 
Now that i have access to my pacman logs, do u have any other suspected package whose update log i should check for?

[reported working date]: https://github.com/wez/wezterm/issues/2294#issuecomment-1339258418

**Comment by Biswa96** [comment] 2023-01-25 19:49
> So, bash might not be the culprit...

bash was never the culprit. bash is a shell, not a terminal emulator.

There is too many questions about your setup. Why are you launching bash directly with wezterm start bash or alacritty -e bash? Use `msys2_shell.cmd` to launch a specific mingw environment. Then just run the `helix` command. The $MINGW_PREFIX/bin/helix is a shell script which launches the actual hx.exe executable.

I have tried to launch helix in alacritty and it worked without any issue.

**Comment by Biswa96** [comment] 2023-01-25 19:58
There is too many questions about your setup. Why are you launching bash directly with wezterm start bash or alacritty -e bash? Use `msys2_shell.cmd` to launch a specific mingw environment. Then just run the `helix` command. The $MINGW_PREFIX/bin/helix is a shell script which launches the actual hx.exe executable.

I have tried to launch helix in alacritty and it worked without any issue.

**Comment by jeremyd2019** [comment] 2023-01-26 05:44
> So, bash might not be the culprit... Now that i have access to my pacman logs, do u have any other suspected package whose update log i should check for?

I would suspect `msys2-runtime`, the terminal/pty/console code in upstream cygwin gets a lot of fixes, and is mostly inscrutable to anyone but the author.

> * How can i install the older version of a package?
>   Again, ideally, i would have wanted to try running git bisect here, but i don't know building etc, so, i will just suffice at running only the prebuild package versions.

In general, look at package files in (in this case) https://repo.msys2.org/msys/x86_64/, pick one, and install it via `pacman -U <URL>`.  It may not be that simple due to dependencies between packages, you could easily get your install into a broken state that way.  Recommend using a temporary installation for such testing so you can just delete it without much loss if things go wrong, or once you're done.

**Comment by yashpalgoyal1304** [comment] 2023-01-26 10:27
> Why are you launching bash directly with wezterm start bash or alacritty -e bash?

i use the context menu from terminals in the explorer "launch terminal here". And so, launching the terminal directly from start is just continuation of that.

> Use `msys2_shell.cmd` to launch a specific mingw environment. Then just run the `helix` command.

i don't use the shell launchers for above said reason. And the shell launcher launched in mintty. The helix runs there perfectly as mentioned in the comment with steps.

> The $MINGW_PREFIX/bin/helix is a shell script which launches the actual hx.exe executable.

Sorry, i forgot to mention that i am using helix from installers, not from the msys.

> I have tried to launch helix in alacritty and in wezterm. It worked in both terminals without any issue.

yes, directly running helix from them doesn't cause an issue. the issue is caused only when helix is launched from bash.

**Comment by yashpalgoyal1304** [comment] 2023-01-26 12:34
> Recommend using a temporary installation

yeah, that seems more like it. 
- or even better yet... i was thinking for doing the investigations with different versions of gfw... 
- as that comes with its own whole environment.... 
- And I hope that, pinpointing it there _may_ help with some knowledge back here at msys2 too, 
- as gfw and msys2 sync with each other quite often...

**Comment by jeremyd2019** [comment] 2023-01-26 18:12
Maybe https://cygwin.com/pipermail/cygwin-patches/2022q2/011935.html ?

But, I don't really understand why you opened an issue and are trying to bisect the *fixing* of an issue rather than the usual trying to track down when an issue was introduced (to try to help find a fix).

**Comment by yashpalgoyal1304** [comment] 2023-01-27 07:17
so, i tried both:

```console
$ disable_pcon=true

$ hx

$ MSYS=disable_pcon

$ hx
```

but helix was working fine still, so...

**Comment by yashpalgoyal1304** [comment] 2023-01-27 16:12
> I don't really understand why you opened an issue and are trying to bisect the _fixing_ of an issue rather than the usual trying to track down when an issue was introduced (to try to help find a fix).

several reasons:
* the fix is recent, some chance of tracking down the version
* who knows how old the bug is
* by tracing the fix, there's some possibility that it will narrow down the scope of the cause of bug a lot (possibly even single it out)

**Comment by yashpalgoyal1304** [comment] 2023-01-27 16:12
> I don't really understand why you opened an issue and are trying to bisect the _fixing_ of an issue rather than the usual trying to track down when an issue was introduced (to try to help find a fix).

several reasons:
* the fix is recent, some chance of tracking down the version
* who knows how old the bug is
* by tracing the fix, there's some possibility that it will narrow down the scope of the cause of bug a lot (possibly even single it out)

**Comment by yashpalgoyal1304** [comment] 2023-01-27 16:12
> I don't really understand why you opened an issue and are trying to bisect the _fixing_ of an issue rather than the usual trying to track down when an issue was introduced (to try to help find a fix).

several reasons:
* the fix is recent, some chance of tracking down the version
* who knows how old the bug is
* by tracing the fix, there's some possibility that it will narrow down the scope of the cause of bug a lot (possibly even single it out)

**Comment by yashpalgoyal1304** [comment] 2023-01-27 16:18
i managed to reproduce the bug with gfw 2.31.1 ... i will try narrow it down to the fixing version... then will file the bug with upstream gfw...

1. install the version of gfw in a test directory (warning: do NOT use the gfw installer version - it will previous install)
2. navigate to gfw/bin in explorer
3. write click > launch wezterm (terminal here)

```console
cmd> hx
<works>

cmd> bash
<launches bash from current (gfw) folder

$ hx
<mentioned bug>
```

**Comment by jeremyd2019** [comment] 2023-01-27 18:52
I think you'll find that the "fix" came with an updated msys2-runtime version (you can get the version, minus patch level, with `uname -r`).  It seems around 2.37 announced dropping vista support, which corresponded to a Cygwin update (which in turn corresponded to an msys2-runtime update).  I would bet that it was probably https://cygwin.com/pipermail/cygwin-patches/2022q2/011935.html that fixed this

**Comment by yashpalgoyal1304** [comment] 2023-01-27 19:04
> you can get the version, minus patch level, with `uname -r`

thanks a lot, was wondering exactly about same and thought it wouldn't be possible.

* I _think_ the bug/fix might be this: gfw [2.37.1] which fixed a _similar-ish?_ bug: "Pasting large amounts of text in Git for Windows' Bash when running inside Windows Terminal" - pretty close description to the issue at hand
* which was mentioned to be caused by this: https://sourceware.org/pipermail/cygwin/2022-June/251764.html
* which as mentioned [here](https://github.com/git-for-windows/git/issues/3936#issuecomment-1175874391) was fixed by this run in msys-runtime: https://github.com/msys2/msys2-runtime/actions/runs/2614940483#artifacts
* https://github.com/git-for-windows/msys2-runtime/pull/45


[2.37.1]: https://github.com/git-for-windows/git/releases/tag/v2.37.1.windows.1

**Comment by jeremyd2019** [comment] 2023-01-27 19:14
The commit that I was mentioning was also part of that PR (https://github.com/git-for-windows/msys2-runtime/pull/45/commits/e4fdb0cb73cc48a2db473b525b6ba0a33ecabf97).

**Comment by yashpalgoyal1304** [comment] 2023-01-27 19:15
> The commit that I was mentioning was also part of that PR ([git-for-windows/msys2-runtime@e4fdb0c](https://github.com/git-for-windows/msys2-runtime/commit/e4fdb0cb73cc48a2db473b525b6ba0a33ecabf97))

awesome.



> so checking `uname -r` may not be very useful.

oh, ohkay. u just saved me tonnes of efforts. i was just about to reinstall all several of those gfw versions 😅

**Comment by yashpalgoyal1304** [comment] 2023-01-27 19:17
so, i guess left part is just to run hx with a runtime just before that pr/commit, and then once again with a runtime after it. right?

i will do it tomorrow. got some other work at hand atm.

**Comment by yashpalgoyal1304** [comment] 2023-01-30 13:48
> [2022-07-22, 2022-12-06]
> Now that i have access to my pacman logs
\- https://github.com/msys2/MSYS2-packages/issues/3515#issuecomment-1404112562

> I would suspect `msys2-runtime`, ...
\- https://github.com/msys2/MSYS2-packages/issues/3515#issuecomment-1404585718

in line with line of investigation in regards to msys2-runtime, indeed there is an update in the required date range:
`msys2-runtime (3.3.5-3 -> 3.3.6-2)`

```logs
[2021-07-25T16:37:10+0000] [ALPM] installed msys2-runtime (3.2.0-14)
[2021-11-01T13:12:22+0530] [ALPM] upgraded msys2-runtime (3.2.0-14 -> 3.2.0-15)
[2022-06-18T13:55:56+0530] [ALPM] upgraded msys2-runtime (3.2.0-15 -> 3.3.5-2)
[2022-07-10T01:31:03+0530] [ALPM] upgraded msys2-runtime (3.3.5-2 -> 3.3.5-3)
[2022-10-07T00:55:56+0530] [ALPM] upgraded msys2-runtime (3.3.5-3 -> 3.3.6-2)
[2022-12-26T21:48:32+0530] [ALPM] upgraded msys2-runtime (3.3.6-2 -> 3.4.3-4)
```

**Closed** 2023-01-31 14:55 UTC
Labels: external

**Comment by yashpalgoyal1304** [comment] 2023-01-31 16:52
**Conclusion:**
This is a summary of all the spaghetti that got splattered unintentionally....

<details>
<summary>Find suspect</summary>

### Initial data:
- Bug on record: [2022-07-22]
- Fix on record: [2022-12-06]
- Visible Trigger: `bash` (but innocent)
- Actual Guilty: `msys2-runtime` : `uname -r`
- Empirical evidence: 
`[2022-10-07] upgraded msys2-runtime (3.3.5-3 -> 3.3.6-2)`

### Available actors for `msys2-runtime`:
- msys2 distribution: environment not controllable
- gfw distribution: (version, date, uname -r)
    + Buggy with [2.36.1.1] (2022-05-09) : 3.3.4-341
    + Buggy with [2.37.0.1] (2022-06-27) : 3.3.4-341
    + Good with [2.37.1.1] (2022-07-12) : 3.3.5-341


[2022-07-22]: https://github.com/wez/wezterm/issues/2294#issue-1315137202
[2022-12-06]: https://github.com/wez/wezterm/issues/2294#issuecomment-1339258418
[2.36.1.1]: https://github.com/git-for-windows/git/releases/tag/v2.36.1.windows.1
[2.37.0.1]: https://github.com/git-for-windows/git/releases/tag/v2.37.0.windows.1
[2.37.1.1]: https://github.com/git-for-windows/git/releases/tag/v2.37.1.windows.1


### Trail for the fix:
- msys2/msys2-runtime#96 <- Build artifacts (expired)
- <-- Bug in Cygwin <- git-for-windows/git#3936
- <-- "amounts of text in gfw bash in win terminal results in garbled text" in GFW [2.37.1.1] Release notes

</details>

<details>
<summary>Verify suspect</summary>

### Tries for getting artifacts:
- Local build: msys2/msys2-runtime#137 : not enough space, go to msys2/MSYS2-packages/discussions/3504
- gh Actions on _temporary_ fork (from that commit) with `on: workflow_dispatch` in workflows/build.yaml file : build failed
_"Error: Process completed with exit code 2."_ Pro'lly require more tweaks in build to reproduce old environment. Not Worth It.

### Things learnt:
pacman
- <tt>/var/log/[pacman.log]</tt> is awesome
- [pacman sync search] for ["exact" package] name in one line precise output is not possible
- OT: [less] is better than more, but both discard colors, maybe `most` retains colors?
- but `most` doesn't exist in msys2 yet

gh-mods:
- [download-directory] doesn't work
- [Refined gh] browser extension exists

gh:
- github.dev : download folders from repos
- gh Codespaces : no [windows containers], [gh-actions] yet

gh-actions:
- [act] : run gh-actions locally on docker exist
- Modify gh-actions for manual running

</details>

----

Hence, Blocked things freed:
- Reinstall msys2 at new location
- Update Wezterm, Helix
- Hence, proceed to other things



[pacman.log]: https://bbs.archlinux.org/viewtopic.php?id=88600
[pacman sync search]: https://duckduckgo.com/?q=pacman+sync+search+precisely&t=vivaldi&ia=web
["exact" package]: https://bbs.archlinux.org/viewtopic.php?id=249213
[less]: https://askubuntu.com/questions/1191862/
[download-directory]: https://download-directory.github.io/
[refined gh]: https://github.com/refined-github "add features on github interface"
[windows containers]: https://github.com/orgs/community/discussions/9977
[gh-actions]: https://github.com/orgs/community/discussions/3455
[act]: https://github.com/nektos/act
