### ISSUE TITLE
Unable to convert `.texi` files

### ISSUE THREAD

**Issue by mmuetzel** [msys2/MSYS2-packages#3014] opened 2021-08-07 08:40 UTC
See also https://github.com/msys2/MSYS2-packages/issues/2596
I'm not sure if that was the correct place to report this issue. So, I'm repeating here:

I'm not able to create .dvi files from .texi files using `texi2dvi`. I've installed `texlive` and `mingw-w64-x86_64-texlive-core` but also tried unsuccessfully with `mingw-w64-x86_64-texlive-full`.

With the attached file, I see the following:
```
$ texi2dvi test.texi
/usr/bin/texi2dvi: texinfo.tex appears to be broken.
This may be due to the environment variable TEX set to something
other than (plain) tex, a corrupt texinfo.tex file, or
to tex itself simply not working.
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021/Built by MSYS2 project) (preloaded format=etex)
 restricted \write18 enabled.
entering extended mode
! I can't find file `txiversion.tex'.
<*> txiversion.tex

(Press Enter to retry, or Control-Z to exit)
Please type another input file name:
! Emergency stop.
<*> txiversion.tex

No pages of output.
Transcript written on texput.log.
/usr/bin/texi2dvi: quitting.
```
The same command with that file successfully creates a .dvi file on Ubuntu 21.04.

Fwiw, the error is the same for `texi2pdf test.texi`.

Am I doing something wrong? How do I successfully convert `.texi` files in MSYS2?

[test.zip](https://github.com/msys2/MSYS2-packages/files/6932259/test.zip)

**Comment by naveen521kk** [comment] 2022-05-23 17:35
Okay, I did some debugging as to why using `:` in the environment variable fails here. First of all, MSYS2 does convert stuff in the environment variable (even other than PATH) to the windows understandable paths, and it is documented here: https://www.msys2.org/docs/filesystem-paths/#windows-unix-path-conversion, so it's nothing wrong in using `:` inside those scripts as they will be handled by the runtime itself when calling native executables. 

Native executable will see the following variables (just printed them through Python)
```
TEXINPUTS="C:\\msys64\\tmp\\tex-test;C:\\msys64\\tmp\\tex-test\\"
TFMFONTS="C:\\msys64\\tmp\\tex-test;C:\\msys64\\tmp\\tex-test\\"
```
it's actually set to
```
/tmp/tex-test:/tmp/tex-test/.:
/tmp/tex-test:/tmp/tex-test/.:
```
This conversion does look good, but I think the environment variables are defined wrong and that's why it errors out. 

When `OSTYPE=MSYS`, the `path_sep` is set to `;` and produces invalid variables which native executables don't understand (and isn't converted by runtime), so I think it falls back to the default search path and everything works fine.
```
TEXINPUTS="/tmp/tex-test;/tmp/tex-test/.;"
TFMFONTS="/tmp/tex-test;/tmp/tex-test/.;"
```

I think this should be reported to maintainers as to what those environment variables should actually be set.

**Comment by mmuetzel** [comment] 2022-05-23 17:39
Tbh, I don't understand much of the internals here. I'd very much appreciate it if you (or someone else) could report that upstream.

**Comment by naveen521kk** [comment] 2022-05-24 13:24
Now I better understand what the issue is, in the `TEXINPUTS` or any env variable that latex uses, trialling `:` or `;` means that the standard library path should be appended to the end, see https://tex.stackexchange.com/a/93733

When MSYS2 runtime converts the `TEXINPUTS` variable to windows understandable paths, it strips the trailing trailing `:`, which causes this entire issue. Not sure what's the best approach here that the upstream can use, or can the runtime can be fixed to just convert the trialling `:` to `;` instead of removing it? If upstream wants to fix this, they would need to `;` as pathsep and use an absolute windows-styled path and not Unix styled ones as they would not be converted.

**Comment by mmuetzel** [comment] 2022-05-24 14:18
Thank you for digging into this!
I most probably don't understand all possible side effects. But I'd assume that the best approach might be to keep trailing path separators when translating between Windows and UNIX path lists.

**Comment by naveen521kk** [comment] 2022-05-31 10:03
Now that https://github.com/msys2/msys2-runtime/pull/95 is merged (and also https://github.com/msys2/MSYS2-packages/pull/3021), the new version runtime should be available soon which should fix the issue.

**Comment by naveen521kk** [comment] 2022-06-03 17:23
This issue is fixed and the runtime has been updated in the repo.

**Closed by naveen521kk** 2022-06-03 17:23 UTC

**Comment by mmuetzel** [comment] 2022-06-03 17:34
Thank you very much for tracking this down and getting it fixed. 🎉
This also works for me now. As a bonus, I no longer need to set TEX either!
