### ISSUE TITLE
No colors on zsh (Raw escape sequence)

### ISSUE THREAD

**Issue by Gpinchon** [msys2/MSYS2-packages#1624] opened 2019-04-26 09:44 UTC
I can't get no colors on ZSH with default configuration.
![noColors](https://user-images.githubusercontent.com/8039212/56799138-8fa57580-6818-11e9-85e4-b016ac064ee8.PNG)

**Comment by cbrt64** [comment] 2019-05-01 03:12
(Note: I have no knowledge of zsh or how to properly configure it, beyond what I found with google.)

Apparently MSYS2's `zsh` package comes without shell configuration, and is inheriting the prompt from whatever shell you start it from (try running zsh from cmd.exe, for example).

MSYS2 has a zsh configuration in the `grml-zsh-config` package. Alternatively, you could add
```
autoload -U promptinit
promptinit
prompt default
```
to your `~/zshrc`. Running `prompt -p` will list prompts you can set other than "default".

**Comment by cbrt64** [comment] 2019-05-02 20:11
From the discussion at #1285, perhaps the most useful suggestion is to use `zsh -l` to properly get a login shell. Note that bash does the same thing in the reverse situation; if you do `zsh --login` followed by `bash` then bash inherits the prompt from zsh. So maybe this is expected behavior for non-login shells?

**Comment by n1kk** [comment] 2019-06-16 18:44
I have the same issue.
![image](https://user-images.githubusercontent.com/5442968/59568183-8944b480-9077-11e9-8f93-88aa66129a58.png)


Was there a solution?

**Comment by n1kk** [comment] 2019-06-16 18:54
I have the same issue.
![image](https://user-images.githubusercontent.com/5442968/59568280-e5f49f00-9078-11e9-971b-0390c99f58ba.png)

Was there any solution to this?

**Comment by hiroakit** [comment] 2020-02-25 12:53
@Gpinchon 
Do you have this problem?
In my environment, I got the color in zsh v5.8 on MSYS2. Please see also the attached gif animation. 
If you feel different, could you write an explanation?

![result](https://user-images.githubusercontent.com/359823/75248285-3ed72280-5817-11ea-928e-77cab301a88f.gif)

@cbrt64 @Alexpux @lazka @Biswa96
I have a suggestion. 
If you don't get Gpinchon's response after few days, Why don’t you close this issue?
Information is so little, no anyone can solve.

**Comment by hiroakit** [comment] 2020-03-03 09:53
@Gpinchon
This is just a friendly reminder that waiting for your reply.

lazka, thanks labeling.

**Comment by hiroakit** [comment] 2020-03-09 14:25
I guess it reproduced. 
Steps to reproduce is here:

1. Run C:\msys64\msys2_shell.cmd -mingw64, logged in with bash
2. Install zsh. Using `Pacman -S zsh`. If you have .zshrc, .zshenv, .zprofile on $HOME, remove it.
3. Type `zsh`, and run it  on bash. So, Running zsh-newuser-install.
4. Reproduce this issue, image is here:

<img width="937" alt="スクリーンショット 2020-03-09 23 23 32" src="https://user-images.githubusercontent.com/359823/76221853-101c6b80-625d-11ea-84c8-de148149bd45.png">

**Comment by hiroakit** [comment] 2020-03-10 15:18
I'm researching though I don't know exactly.
Checking it that happen with other platform, i got similar case on Ubuntu.
Probably due to zsh, there is no evidence.

Operation is here:
<img width="732" alt="スクリーンショット 2020-03-11 0 03 09" src="https://user-images.githubusercontent.com/359823/76327746-b9cb2d80-632d-11ea-84b0-b97f74fefd9a.png">
<img width="734" alt="スクリーンショット 2020-03-11 0 03 26" src="https://user-images.githubusercontent.com/359823/76327754-bc2d8780-632d-11ea-8d8f-89a138667673.png">
<img width="736" alt="スクリーンショット 2020-03-11 0 03 41" src="https://user-images.githubusercontent.com/359823/76327762-bdf74b00-632d-11ea-92f2-b7959ac5be1d.png">

**Comment by hiroakit** [comment] 2020-04-20 01:19
This issue has been fixed in #1903. 
Please update to `msys/zsh 5.8-3` and check it out.

**Closed by hiroakit** 2020-04-20 01:19 UTC
