### ISSUE TITLE
ssh.exe: error while loading shared libraries: ?

### ISSUE THREAD

**Issue by kuklis** [msys2/MSYS2-packages#1588] opened 2019-03-07 09:06 UTC
Just installed msys2-x86_64-20180531
Installed openssh. First of all, libopenssl should be a dependency, ssh command was missing it.

After installing libopenssl too, I'm getting this error message:
```
$ ssh
C:/msys64/usr/bin/ssh.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

See last line:

```
$ ldd /usr/bin/ssh
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7ffd2dfc0000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7ffd2ca50000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7ffd2a7a0000)
        msys-crypto-1.1.dll => /usr/bin/msys-crypto-1.1.dll (0x58b980000)
        msys-gssapi-3.dll => /usr/bin/msys-gssapi-3.dll (0x4f53c0000)
        msys-z.dll => /usr/bin/msys-z.dll (0x522fe0000)
        msys-gcc_s-seh-1.dll => /usr/bin/msys-gcc_s-seh-1.dll (0x5e8160000)
        msys-heimntlm-0.dll => /usr/bin/msys-heimntlm-0.dll (0x5fe970000)
        msys-heimbase-1.dll => /usr/bin/msys-heimbase-1.dll (0x5889a0000)
        msys-2.0.dll => /usr/bin/msys-2.0.dll (0x180040000)
        msys-asn1-8.dll => /usr/bin/msys-asn1-8.dll (0x4901d0000)
        msys-roken-18.dll => /usr/bin/msys-roken-18.dll (0x5fe2a0000)
        msys-com_err-1.dll => /usr/bin/msys-com_err-1.dll (0x419420000)
        msys-krb5-26.dll => /usr/bin/msys-krb5-26.dll (0x4e6ec0000)
        ??? => ??? (0x2e20000)
```

**Comment by Alexpux** [comment] 2019-03-20 05:15
@kuklis use something like ````Dependency walker```` to see what library is missing

**Comment by iain-waugh** [comment] 2019-05-03 06:18
I see the same thing if I use an MSys2 shell to run something I compiled under MinGW64.
Here's what I see under a MinGW64 shell:
```Fri May 03 16:11:42 MINGW64 /c/Work/sw/OpenSource/jctvc-hm/bin
$ldd TAppEncoderStatic.exe
        ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x77640000)
        kernel32.dll => /c/Windows/system32/kernel32.dll (0x77520000)
        KERNELBASE.dll => /c/Windows/system32/KERNELBASE.dll (0x7fefd1b0000)
        msvcrt.dll => /c/Windows/system32/msvcrt.dll (0x7fefea00000)
        libgcc_s_seh-1.dll => /mingw64/bin/libgcc_s_seh-1.dll (0x61440000)
        libwinpthread-1.dll => /mingw64/bin/libwinpthread-1.dll (0x64940000)
        libstdc++-6.dll => /mingw64/bin/libstdc++-6.dll (0x6fc40000)
        USER32.dll => /c/Windows/system32/USER32.dll (0x77420000)
        GDI32.dll => /c/Windows/system32/GDI32.dll (0x7fefeea0000)
        LPK.dll => /c/Windows/system32/LPK.dll (0x7fefd7a0000)
        USP10.dll => /c/Windows/system32/USP10.dll (0x7fefeaf0000)

```
Running `./TAppEncoderStatic.exe` works here.

Here's what I see under an MSys2 shell:
```Fri May 03 11:46:23 MSYS /c/Work/sw/OpenSource/jctvc-hm/bin
$ldd TAppEncoderStatic.exe
        ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x77640000)
        kernel32.dll => /c/Windows/system32/kernel32.dll (0x77520000)
        KERNELBASE.dll => /c/Windows/system32/KERNELBASE.dll (0x7fefd1b0000)
        msvcrt.dll => /c/Windows/system32/msvcrt.dll (0x7fefea00000)

Fri May 03 16:12:13 MSYS /c/Work/sw/OpenSource/jctvc-hm/bin
$./TAppEncoderStatic.exe
C:/Work/sw/OpenSource/jctvc-hm/bin/TAppEncoderStatic.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

**Comment by drazde** [comment] 2019-10-29 12:35
I have the same issue, also typing `ls` the error is the same
~~~
C:/Program Files (x86)/OpenSSH/bin/ls.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
~~~

**Comment by StarWolf3000** [comment] 2019-10-30 06:29
@drazde Please only report issues here, if you're using MSYS2. Your OpenSSH is not connected to MSYS2 in any way. Report it to the OpenSSH for Windows maintainers.

**Comment by drazde** [comment] 2019-10-30 07:32
> 
> 
> @drazde Please only report issues here, if you're using MSYS2. Your OpenSSH is not connected to MSYS2 in any way. Report it to the OpenSSH for Windows maintainers.

I'm sorry, I have not seen the full path :( of the error...

**Comment by miek770** [comment] 2022-12-22 20:05
Has anyone found a fix? I have a brand new MSYS2 installation on a brand new Windows 10 installation, and get a similar error:

```
$ ssh user@host
D:/msys64/usr/bin/ssh.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

`ldd` returns no "?" library though:

```
$ ldd /usr/bin/ssh
        ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x7ff97bab0000)
        KERNEL32.DLL => /c/Windows/System32/KERNEL32.DLL (0x7ff97b270000)
        KERNELBASE.dll => /c/Windows/System32/KERNELBASE.dll (0x7ff979610000)
        msys-gssapi-3.dll => /usr/bin/msys-gssapi-3.dll (0x4f53c0000)
        msys-crypto-3.dll => /usr/bin/msys-crypto-3.dll (0x4356f0000)
        msys-2.0.dll => /usr/bin/msys-2.0.dll (0x180040000)
        msys-2.0.dll => /usr/bin/msys-2.0.dll (0xd90000)
        msys-z.dll => /usr/bin/msys-z.dll (0x522fe0000)
        msys-asn1-8.dll => /usr/bin/msys-asn1-8.dll (0x4901d0000)
        msys-com_err-1.dll => /usr/bin/msys-com_err-1.dll (0x419420000)
        msys-heimntlm-0.dll => /usr/bin/msys-heimntlm-0.dll (0x5fe970000)
        msys-heimbase-1.dll => /usr/bin/msys-heimbase-1.dll (0x5889a0000)
        msys-hcrypto-4.dll => /usr/bin/msys-hcrypto-4.dll (0x4a4450000)
        msys-krb5-26.dll => /usr/bin/msys-krb5-26.dll (0x4e6ec0000)
        msys-roken-18.dll => /usr/bin/msys-roken-18.dll (0x5fe2a0000)
        msys-roken-18.dll => /usr/bin/msys-roken-18.dll (0x170000)
        msys-roken-18.dll => /usr/bin/msys-roken-18.dll (0x170000)
        msys-wind-0.dll => /usr/bin/msys-wind-0.dll (0x497010000)
        msys-gcc_s-seh-1.dll => /usr/bin/msys-gcc_s-seh-1.dll (0x5e8160000)
        msys-crypt-0.dll => /usr/bin/msys-crypt-0.dll (0x43dbf0000)
        msys-hx509-5.dll => /usr/bin/msys-hx509-5.dll (0x47f610000)
```

P.s.: I also had to install `libopenssl` manually.

**Comment by Biswa96** [comment] 2022-12-22 20:09
This seems to be an old issue. I can not reproduce it in my setup. Make sure that no antivirus or antimalware software has not modified or deleted a file in msys2. You can exclude msys2 installation directory in those antivirus software.

**Comment by miek770** [comment] 2022-12-23 00:56
> This seems to be an old issue. I can not reproduce it in my setup. Make sure that no antivirus or antimalware software has not modified or deleted a file in msys2. You can exclude msys2 installation directory in those antivirus software.

Thanks for the quick response, but it is a brand new installation with no antivirus / antimalware on the system. Must I do this exclusion in Windows Defender (or another Windows 10 basic utility)?

**Comment by Biswa96** [comment] 2022-12-23 03:58
> Must I do this exclusion in Windows Defender (or another Windows 10 basic utility)?

Windows Defender is the main antagonist here :)

**Comment by echoxxzz** [comment] 2023-01-03 23:06
I've done a clean install of MSYS2 and I have Windows Defender completely disabled and I still get the missing ? shared library.

**Comment by Biswa96** [comment] 2023-01-04 04:36
⚠️ Please DO NOT use any other websites to download DLLs. Many of the websites give you free malware. ⚠️ 

> library that ssh.exe is looking for is called msys-crypto-1.1.dll.

You are probably using older SSH. Update the packages with `pacman -Syyu` command. msys-crypto-3.dll is the latest one provided by libopenssl package. It is already a dependency of openssh. So, updating the packages and installing openssh can fix the missing shared libraries message.

Closing as not being an issue.

**Closed by Biswa96** 2023-01-04 04:36 UTC

**Comment by aki-kuramoto** [comment] 2023-01-05 06:57
I met same issue on brand new installation of msys2-x86_64-20221216.exe but the command solved it.

```
$ ssh --version
C:/msys64/usr/bin/ssh.exe: error while loading shared libraries: msys-crypto-3.dll: cannot open shared object file: No such file or directory

$ pacman -Syyu

$ ssh --version
ssh: unknown option brabrabra
```

Thank you!!

**Comment by echoxxzz** [comment] 2023-01-05 20:28
Today I tried a clean install of MSYS2 and now I don't even get the problem anymore so something upstream got fixed. But I can confirm that if I removed that dll and did the pacman -Syyu it did fix the problem for me.

**Comment by joseluu** [comment] 2023-02-28 16:06
> I've done a clean install of MSYS2 and I have Windows Defender completely disabled and I still get the missing ? shared library.
> 
> Edit: I ran Sysinternals Process Monitor and the ? library that ssh.exe is looking for is called msys-crypto-1.1.dll. I ran pacman -Fy and no current packages contain this dll. I ended up getting if from [here](https://www.pconlife.com/download/otherfile/288057/27db897c1d4a1489192c9df2e8c6407b/) and now ssh works.

Thanks this fix worked for me as well, to no avail I had done a pacman -Syu before and ssh only referenced msys-crypto-3.dll which was present.

**Comment by SlySven** [comment] 2023-04-07 13:20
Yeah - this is all down to the switch away from OpenSSL from 1.1 to 3.x (indeed the former was declared EoL a few days ago - see [here](https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/). If you are trying to run an MSYS2 + Mingw-w64 system but have "added" in elements from the Git-For-Window project you are going to have problems...
